#app
server:
    port: 8080
    tomcat:
      uri-encoding: UTF-8


#spring
spring:
  devtools:
    restart:
      #开启热更新
      enabled: true
      #additional-paths: src/main/java

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true


  datasource:
     #oracle配置
#     driver-class-name: oracle.jdbc.OracleDriver
#     url: jdbc:oracle:thin:@47.104.93.24:1521:orcl
#     username: uniview
#     password: uniview123

    url: jdbc:mysql://112.124.44.80:3306/demo?characterEncoding=UTF-8
    username: root
    password: long@190807
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**
  #配置i18n资源文件供thymeleaf使用
  messages:
    basename: i18n/messages



#mybatis
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/longzongqin/demo/mapper/xml/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/longzongqin/demo/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.longzongqin.demo.entity
  typeEnumsPackage: com.longzongqin.demo.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.longzongqin.demo.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'


#logging
#logging:
#  level: warn


